{{.ChecksumName}} Checksum Data

{{range $name, $chksum:= .Checksums}}
{{$name}}
{{range $line := (multiline $chksum 32)}}{{blocks $line " " 4}}
{{end}}
{{end}}

generated by TBBS (info-age GmbH, Basel)