Listen = "localhost:80"
TLS = false
PrivateKey = [ "C:/daten/keys/putty_ed25519.priv.openssh", "C:/daten/keys/putty_2048.priv.openssh", "C:/daten/keys/hek.priv.openssh" ]
Logfile = ""
Loglevel = "DEBUG"
Logformat = "%{time:2006-01-02T15:04:05.000} %{module}::%{shortfunc} [%{shortfile}] > %{level:.5s} - %{message}"

Tempdir = "c:/temp/bagit"
Basedir = "c:/temp/bagit"
Keydir = "c:/temp/bagit/keys"
Reportdir = "c:/daten/go/dev/tbbs/report"
DBFolder = "c:/temp/bagit/badger"

# remove temporary files after bagit creation
Cleanup = false

# checksums which need to be created for bagit
Checksum  = ["md5", "sha512"]

#ingest only stuff
ingestloc = "temp"

[tunnel.main]
    user = "root"
    privatekey = "C:/daten/keys/putty_ed25519.priv.openssh"
    [tunnel.main.endpoint]
        port = 22
        host = "ba14ns21403.fhnw.ch"
    [tunnel.main.forward.mysql.local]
        port = 3308
        host = "localhost"
    [tunnel.main.forward.mysql.remote]
        port = 3306
        host = "v000306.adm.ds.fhnw.ch"

[db]
    #[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
    dsn = "tbbs:hcpOLPk64DtgNXLR@tcp(localhost:3308)/tbbs?parseTime=true"
    connMaxTimeout = "4h"
    schema = "tbbs"
